### PR TITLE
Enable OAuth, add Home and Charts menu + bugfixes

### PR DESCRIPTION
**Pull request by fischcode**
This time, there are lots of changes, some quite recent and not fully tested. Reason for submitting right now is that the update to parser.py is required to keep the addon working:
- Apply an improved fix to PyTube parser.py from https://github.com/sluggish-yard/pytube-saguaro/pull/5/commits/e91d5281c06cb7236c66053c3ce5561e647598a6
- Update ytmusicapi to version `1.2.1`
- Enable OAuth login into ytmusicapi
- Add 'Home' menu item to YtMusic Library menu
- Add experimental 'Charts' menu item to YtMusic Library menu (songs don't work yet)
- Show more detailed song information
- Add albumart to songs in playlist when adding entire albums / singles
- Add context menu items 'Play' / 'Play next' / 'Add to queue' to songs
- Add option to turn off colored titles (for headless operation of Kodi)
- Add wrapper class around YtMusic Library results exposing a uniform interface for results obtained from internal storage and from different API calls

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Woah, from reviewing your changes, you made alot of changes, Thank you very much. Sorry i have not been active working on youtube music but im glad we have you working on it. You know i just noticed you were not a Collaborator so i sent you an invite so that way you can make alot of commit changes and stuff without it being in a pull. Again, Huge thank you.

**Comment by fischcode** [comment]
Hi 

 

I have successfully uploaded some more improvements to GitHub but don’t quite know what it takes to have the code attached to a new release: Do I manually have to create the archives and attach them? Does GitHub do this automatically? And what does it take to update the YTMusic Repository? Maybe you can help me out with a hint or two 😊

Thanks a lot in advance and best regards!



 

Von: Goldenfreddy0703 ***@***.***> 
Gesendet: Freitag, 29. September 2023 22:50
An: Goldenfreddy0703/plugin.audio.ytmusic.exp ***@***.***>
Cc: fischcode ***@***.***>; Author ***@***.***>
Betreff: Re: [Goldenfreddy0703/plugin.audio.ytmusic.exp] Enable OAuth, add Home and Charts menu + bugfixes (PR #29)

 

Woah, from reviewing your changes, you made alot of changes, Thank you very much. Sorry i have not been active working on youtube music but im glad we have you working on it. You know i just noticed you were not a Collaborator so i sent you an invite so that way you can make alot of commit changes and stuff without it being in a pull. Again, Huge thank you.

**Comment by Goldenfreddy0703** [comment]
> Hi I have successfully uploaded some more improvements to GitHub but don’t quite know what it takes to have the code attached to a new release: Do I manually have to create the archives and attach them? Does GitHub do this automatically? And what does it take to update the YTMusic Repository? Maybe you can help me out with a hint or two 😊 Thanks a lot in advance and best regards!

Hey so basically I manually create a new release and github automatically uses the latest commit to release and all. For the repo, I have a automation script to update youtube music addon to the latest version. When you wanna make a release, just make sure to update the version number in the addon.xml and make sure the changelog is updated as well and I can run my automation script for the repo and all.

**Comment by Goldenfreddy0703** [comment]
Oh btw from looking at your latest commit, it looks like you updated the version number and change so let me go ahead and run my script and it should be on the repo in a few min. 

Thank you 😊

**Comment by fischcode** [comment]
Thanks you very much for your explanations. I therefore published the Release I had prepared and GitHub added the .zip and .tar.gz archives as expected :-)
Thus, all is now set for updating the repo(s): Thanks a lot in advance!

Have a great day!


 

Gesendet: Freitag, 20. Oktober 2023 um 01:00 Uhr
Von: "Goldenfreddy0703" ***@***.***>
An: "Goldenfreddy0703/plugin.audio.ytmusic.exp" ***@***.***>
Cc: "fischcode" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Goldenfreddy0703/plugin.audio.ytmusic.exp] Enable OAuth, add Home and Charts menu + bugfixes (PR #29)


 

Oh btw from looking at your latest commit, it looks like you updated the version number and change so let me go ahead and run my script and it should be on the repo in a few min.

Thank you 😊

**Comment by Goldenfreddy0703** [comment]
Hey thanks you too and you did a great job on the release, thank you

**Pull request merged**
